### ISSUE TITLE
Readme images return 404 (not found)

### ISSUE THREAD

**Issue by Primajin** [NerdyPepper/taizen#22] opened 2021-01-20 05:47 UTC
The images in the readme.md can't be found.

One points to a service called 0x0 that seems to have issues, the other link points to nerdypepper.me which also seems to not hold the images anymore.

According to @pickfire this is not a duplicate of #18

**Comment by pickfire** [comment] 2021-01-20 14:46
Duplicate of #18

**Closed as completed** 2021-01-20 15:06 UTC
